## ğŸ§© environment-sim-only.yamlï¼ˆä»¿çœŸè½»é‡ç‰ˆï¼‰

> åªéœ€è¦è·‘ `simulation.py` çš„åŒå­¦ç”¨è¿™ä¸ªï¼›æ²¡æœ‰å®‰è£… SB3ã€wandb ç­‰

```yaml
name: me5418
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pip:
      - mujoco==3.1.5
      - gymnasium[all]
      - imageio
      - imageio-ffmpeg
      - opencv-python